spring:
  # tomcatを起動しない
  main.web-application-type: none
  # jacksonでBigDecimalを指数表現なしで出力
  jackson.generator.write_bigdecimal_as_plain: true

# camel常時実行
camel.springboot.main-run-controller: true

# ログレベル
#logging.level:
#  # 通常設定
#  "com.hitachi.droneroute.wdl": info
#  # デバッグ設定
#  "com.hitachi.droneroute.wdl": debug

# ルート
route:
  # 気象業務支援センター
  jmbsc:
    # 降水量実況
    precipitation-live:
      # 自動起動(true:起動、false:起動しない)
      auto-startup: true
      # 実行間隔※10秒=10*1000=10,000ミリ秒
      interval: 10_000
      # 実行間隔※10分=10*60*1000=600,000ミリ秒
      # interval: 600_000
    # 降水量予報
    precipitation-forecast:
      # 自動起動(true:起動、false:起動しない)
      auto-startup: true
      # 実行間隔※10秒=10*1000=10,000ミリ秒
      interval: 10_000
      # 実行間隔※10分=10*60*1000=600,000ミリ秒
      # interval: 600_000
    # 風速
    wind-speed:
      # 自動起動(true:起動、false:起動しない)
      auto-startup: true
      # 実行間隔※10秒=10*1000=10,000ミリ秒
      interval: 10_000
      # 実行間隔※10分=10*60*1000=600,000ミリ秒
      # interval: 600_000

# SFTP
sftp:
  # ホスト
  host: localhost
  # ポート
  port: 22
  # ユーザ名
  username: dpls01
  # パスワード
  password: Le2tmYvc
  # known_hostsファイル確認※true=確認する(known_hostsファイルにパスを記載)、false=確認しない
  known-hosts-check: false
  # known_hostsファイル※known_hostsファイル確認がtrueの場合のみ有効
  known-hosts: ~/.ssh/known_hosts
  # ルートディレクトリ
  root-directory:
    # 降水ナウキャスト(5分)
    nowc: /sftp/weather/nowc
    # 降水短時間予報
    srf: /sftp/weather/srf
    # 局地数値予報モデル
    lfm: /sftp/weather/rjtd
# GRIB2
grib2:
  # ファイル名
  file-name:
    # フォーマット
    format:
      # 降水ナウキャスト(5分)
      nowc: Z__C_RJTD_\d{14}_NOWC_GPV_Ggis1km_Prr05lv_FH0005-0100_grib2.bin
      # 降水短時間予報
      srf: Z__C_RJTD_\d{14}_SRF_GPV_Ggis1km_Prr60lv_FH01-06_grib2.bin
      # 局地数値予報モデル
      lfm: Z__C_RJTD_\d{14}_LFM_GPV_Rjp_Lsurf_FH\d{4}_grib2.bin
    # 日時フォーマット
    date-time:
      # フォーマット
      format: yyyyMMddHHmmss
      # オフセット
      offset: 10
      # 長さ
      length: 14
    # 予報時間
    forecast-time:
      # 局地数値予報モデル
      lfm:
        # オフセット
        offset: 45
        # 長さ
        length: 4
        # 値
        values: "{'0130','0200','0230','0300','0330','0400','0430','0500','0530','0600','0630'}"
  # 共通
  common:
    # 作成ステータス
    create-status:
      # オフセット
      offset: 35
      # 長さ
      length: 1
      # 現業プロダクト(本番用)
      operational-product: 0
    # データサイズ(第0,8節除く)
    data-size: 
      # オフセット
      offset: 0
      # 長さ
      length: 4
    # 節番号
    section-number:
      # オフセット
      offset: 4
      # 長さ
      length: 1
  # 第０節
  section0:
    # データサイズ
    data-size: 16
    # 全体のデータサイズ
    all-data-size:
      # オフセット
      offset: 8
      # 長さ
      length: 8
  # 第1節
  section1:
    # 参照日時
    ref-date-time:
      # オフセット
      offset: 12
      # 長さ
      length: 7
  # 第2節はデータがないため定義なし
  # 第3節
  section3:
    # 格子点
    grid-point:
      # 共通
      common:
        # 長さ
        length: 8
        # 座標の尺度因子
        coordinate-scale-factor: -6
      # 数
      count:
        # オフセット
        offset: 30
      # 最初
      first:
        # オフセット
        offset: 46
      # 間隔
      interval:
        # オフセット
        offset: 63
  # 第4節
  section4:
    # パラメータ
    parameter:
      # オフセット
      offset: 9
      # 長さ
      length: 2
    # 予報時間
    forecast-time:
      # オフセット
      offset: 18
      # 長さ
      length: 4
    # 終了日時
    end-date-time:
      # オフセット
      offset: 34
      # 長さ
      length: 7
  # 第5節
  section5:
    # 降水ナウキャスト(5分)、降水短時間予報
    nowc-srf:
      # 1データのビット数
      bit-count:
        # オフセット
        offset: 11
        # 長さ
        length: 1
      # 今回の圧縮に用いたレベルの最大値
      current-max-level:
        # オフセット
        offset: 12
        # 長さ
        length: 2
      # 代表値
      rep-value:
        # オフセット
        offset: 16
    # 局地数値予報モデル
    lfm:
      # 単純圧縮
      simple-compression:
        # オフセット
        offset: 11
        # 長さ
        length: 9
  # 第6節
  section6:
    # ビットマップ指示符
    bitmap:
      # オフセット
      offset: 5
  # 第7節
  section7:
    # オクテット列
    octet-sequence:
      # オフセット
      offset: 5
  # 第8節
  section8:
    # データサイズ
    data-size: 4

# 提供する情報
provide-content:
  # 降水ナウキャスト
  nowc:
    # 地域CSV※CSV形式:最小緯度,最小経度,最大緯度,最大経度
    area-csvs: &area-csvs
      # 範囲外(=埼玉県秩父地域+20度)
      #- 55.822267,158.565063,56.206052,159.270248
      # 埼玉県秩父地域
      - 35.822267,138.565063,36.206052,139.270248
      # 静岡県浜松市
      - 34.640377,137.695531,35.305039,138.050692
    # 最低予報時間(分)
    min-forecast-time: 0
    # パラメータカテゴリ※1:湿度
    parameter-category: 1
    # パラメータ番号リスト※203:降水強度レベル値
    parameter-numbers:
      - 203
  # 降水量短時間予報
  srf:
    # 地域CSV※CSV形式:最小緯度,最小経度,最大緯度,最大経度
    area-csvs: *area-csvs
    # 最低予報時間(分)
    min-forecast-time: 60
    # パラメータカテゴリ※1:湿度
    parameter-category: 1
    # パラメータ番号リスト※200:1時間降水量レベル値
    parameter-numbers:
      - 200
  # 局地数値予報モデル
  lfm:
    # 地域CSV※CSV形式:最小緯度,最小経度,最大緯度,最大経度
    area-csvs: *area-csvs
    # 最低予報時間(分)
    min-forecast-time: 0
    # パラメータカテゴリ※2:運動量
    parameter-category: 2
    # パラメータ番号リスト※2:風のu成分、3:風のv成分
    parameter-numbers:
      - 2
      - 3

# REST
rest:
  # タイムアウト
  timeout:
    # 接続タイムアウト時間（ミリ秒）
    connect: 10000
    # 読み取りタイムアウト時間（ミリ秒）
    read: 10000
  # 最大リトライ回数
  max-retry-count: 3
  # NECコンソ
  nec:
    # 種別
    type:
      # 降水量実況
      apcp-live: APCP_LIVE
      # 降水量予報
      apcp-forecast: APCP_FORECAST
      # 東西風速
      ugrd: UGRD
      # 南北風速
      vgrd: VGRD
    # 予報日時形式
    forecast-date-time-format: yyyyMMddHHmmss
    # エンドポイント＠ローカル
    endpoint: http://localhost:5005/api/wind